export const SW = {
  welcome: "Karibu",
  continue: "Endelea",
  next: "Ifuatayo",
  previous: "Iliyotangulia",
  correct: "Sahihi!",
  incorrect: "Si sahihi. Jaribu tena!",
  tryAgain: "Jaribu tena",
  listen: "Sikiliza",
  speak: "Sema",
  yourTurn: "Zamu yako",
  lessonComplete: "Somo limekamilika!",
  xpEarned: "XP uliyopata",
  streak: "Mfululizo",
  dailyGoal: "Lengo la kila siku",
  settings: "Mipangilio",
  profile: "Wasifu",
  logout: "Toka",
  premium: "Premium",
  upgrade: "Boresha",
  payment: "Malipo",
  referral: "Rufaa",
  share: "Shiriki",
  greeting: "Habari",
  continueLearning: "Endelea kujifunza",
  todaysPlan: "Mpango wa leo",
  viewAll: "Ona zote",
  lesson: "Somo",
  aiConversation: "Mazungumzo ya AI",
  newWords: "Maneno mapya",
} as const;